mode: auto

avatar:
  url: /images/avatar.jpg
  status:
    enable: true
    message: Change the world.

reward:
  enable: false

social:
  - name: GitHub
    link: https://github.com/x-leehe
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:a2956962139@outlook.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=587453912
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: 哔哩哔哩
    link: https://space.bilibili.com/364290179
    icon: ri:bilibili-line
    color: '#FF8EB3'

banner:
  enable: true
  title: 
    - X
    - Lee
    - He
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

trianglify:
  enable: true
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

medium_zoom: true

pages:

creative_commons:
  clipboard: true

footer:
  powered:
    enable: true
  custom_text: <a href="https://icp.gov.moe/?keyword=20220374" target="_blank">萌ICP备20220374号</a>

comment:
  enable: true
  tips:
    - 若您想及时得到回复提醒，建议跳转 GitHub Issues 评论。
    - 若没有本文 Issue，您可以使用 Comment 模版新建。

utterances:
  enable: true
  repo: x-leehe/x-leehe.github.io
  issue-term: pathname
  # label: comment
  theme: github-light

